### ISSUE TITLE
请问你用的tensorflow是哪个版本？

### ISSUE THREAD

**Issue by godtang** [hjptriplebee/Chinese_poem_generator#11]
我使用了2.0和1.4，均不能运行
1.4报错No module named 'tensorflow.compat'
2.0报错module 'tensorflow' has no attribute 'placeholder'，根据https://blog.csdn.net/flowingfog/article/details/93597697修改之后，报错module 'tensorflow_core.compat.v1' has no attribute 'contrib'

**Comment by godtang** [comment]
1.2也试了，报1.4相同的错误

**Comment by hjptriplebee** [comment]
能把完整的stack贴上来吗？应该是版本的问题，这个repo我也一年没更新了

**Comment by godtang** [comment]
不好意思，我在2.0测试的时候修改了代码，用1.4和1.2测试的时候没有还原代码，导致报错。
非常抱歉，浪费你时间了
