### ISSUE TITLE
如何指定自动生成的诗是七言，五言等

### ISSUE THREAD

**Issue by rubby33** [hjptriplebee/Chinese_poem_generator#3]
请问，如何指定自动生成的诗是七言，五言等？
如何制定是四句 or 八句诗词。
哪个参数控制？

**Comment by rubby33** [comment]
请问有这个功能吗？ @hjptriplebee  谢谢你

**Comment by hjptriplebee** [comment]
@rubby33 目前没有，但是实现起来还是比较简单的，两种方案：
1. 训练数据做一遍分离，五言和七言的分开分别训练各自的模型；
2. 在训练数据开头加入五或七的特定标识符，让模型自己学什么是五言，什么是七言。如果生成五言的话开头指定五言标识符，否则指定七言标识符
