### ISSUE TITLE
Support for windows machine

### ISSUE THREAD

**Issue by tanzhangwen** [hjptriplebee/Chinese_poem_generator#6]
In data.py, it will be better to add encoding when open the file in case for a computer whose default encoding is not utf-8.
        file = open(filename, "r", **encoding='utf-8'**)

Otherwise, there will be error: 
UnicodeDecodeError: 'charmap' codec can't decode byte

**Comment by hjptriplebee** [comment]
编码方式在写入文件的时候就已经决定了，和你在什么机器上打开没有关系，如果出现这样的问题，请检查：1. open的文件编码方式是什么，2.是不是使用了python2

**Comment by tanzhangwen** [comment]
Just a suggestion to you that adding it will make your program robust. This is my experience and I just want to share with you instead of seeking your advice. Never mind, please ignore it.
